// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtZs8IJrMW_doH9nZGwJeZKWy8gdFcMDQ',
    appId: '1:213720031718:web:5d8e6808d29815c73c3627',
    messagingSenderId: '213720031718',
    projectId: 'e-cell-vishnu-website',
    authDomain: 'e-cell-vishnu-website.firebaseapp.com',
    storageBucket: 'e-cell-vishnu-website.firebasestorage.app',
    measurementId: 'G-B68B6FXGK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwCfcZPK3t1mQsn8Wp69GcLQazEHbXwr0',
    appId: '1:213720031718:android:182d341f868a334a3c3627',
    messagingSenderId: '213720031718',
    projectId: 'e-cell-vishnu-website',
    storageBucket: 'e-cell-vishnu-website.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeINOSoqc4XWf61p_-605Bu1_lS7SHp2c',
    appId: '1:213720031718:ios:abcc83aa66118b893c3627',
    messagingSenderId: '213720031718',
    projectId: 'e-cell-vishnu-website',
    storageBucket: 'e-cell-vishnu-website.firebasestorage.app',
    androidClientId: '213720031718-6aua9c2ubi61upj6m7i3p2h321s3crb4.apps.googleusercontent.com',
    iosClientId: '213720031718-i0de9d550ueq622jg1jlq9bgmn5k59tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCellWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeINOSoqc4XWf61p_-605Bu1_lS7SHp2c',
    appId: '1:213720031718:ios:abcc83aa66118b893c3627',
    messagingSenderId: '213720031718',
    projectId: 'e-cell-vishnu-website',
    storageBucket: 'e-cell-vishnu-website.firebasestorage.app',
    androidClientId: '213720031718-6aua9c2ubi61upj6m7i3p2h321s3crb4.apps.googleusercontent.com',
    iosClientId: '213720031718-i0de9d550ueq622jg1jlq9bgmn5k59tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCellWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtZs8IJrMW_doH9nZGwJeZKWy8gdFcMDQ',
    appId: '1:213720031718:web:2a51d0f51d2ac6b83c3627',
    messagingSenderId: '213720031718',
    projectId: 'e-cell-vishnu-website',
    authDomain: 'e-cell-vishnu-website.firebaseapp.com',
    storageBucket: 'e-cell-vishnu-website.firebasestorage.app',
    measurementId: 'G-9JMJ7L8WE2',
  );
}
